import heroImage from "../../../shared/assets/images/hero/hero.jpg";
import type { Event } from "./event";

export const mockEvents: Event[] = [
    {
        id: "evt-neon-eclipse-2026",
        slug: "neon-eclipse",
        title: "Neon Eclipse",
        subtitle: "Una noche de electronica, visuales inmersivos y energia al limite.",
        description:
            "Neon Eclipse reune DJs nacionales, barras invitadas y una produccion visual de alto impacto para vivir una noche completa en la ciudad.",
        location: "Queretaro",
        venueName: "Distrito Vivo",
        address: "Av. Constituyentes 102, Centro",
        city: "Queretaro",
        date: "24 Oct 2026",
        time: "20:00",
        price: 890,
        image: heroImage,
        category: "Musica",
        status: "available",
        organizer: "Evenxa Nights",
        capacity: 1200,
        tags: ["Electronica", "Visuales", "After"],
        highlights: [
            "Escenario principal con visuales inmersivos",
            "Acceso digital desde tu cuenta Evenxa",
            "Zona de alimentos y barras dentro del venue",
        ],
        schedule: [
            {
                time: "20:00",
                label: "Apertura de puertas",
                description: "Ingreso general, activacion de barras y zona de foto.",
            },
            {
                time: "21:30",
                label: "Warm up",
                description: "Set de apertura con talento local.",
            },
            {
                time: "23:00",
                label: "Show principal",
                description: "Presentacion central con produccion audiovisual completa.",
            },
        ],
        ticketTiers: [
            {
                id: "general",
                name: "General",
                price: 890,
                description: "Acceso al evento y zonas generales.",
                available: true,
            },
            {
                id: "vip",
                name: "VIP",
                price: 1490,
                description: "Acceso preferente y zona elevada.",
                available: true,
            },
        ],
        policies: [
            "Evento para mayores de 18 anos.",
            "El boleto digital se valida una sola vez en acceso.",
            "No se permite el ingreso con alimentos o bebidas externas.",
        ],
    },
    {
        id: "evt-midnight-city-tour-2026",
        slug: "midnight-city-tour",
        title: "Midnight City Tour",
        subtitle: "Recorre la ciudad de noche con musica, paradas sorpresa y crew invitado.",
        description:
            "Midnight City Tour combina transporte, experiencias urbanas y una ruta curada por hotspots de la CDMX para descubrir la ciudad de otra forma.",
        location: "CDMX",
        venueName: "Punto Reforma",
        address: "Paseo de la Reforma 222, Juarez",
        city: "Ciudad de Mexico",
        date: "12 Nov 2026",
        time: "19:30",
        price: 1200,
        image: heroImage,
        category: "Experiencias",
        status: "available",
        organizer: "Evenxa Experiences",
        capacity: 180,
        tags: ["Tour", "Urbano", "Noche"],
        highlights: [
            "Ruta nocturna con staff y transporte incluido",
            "Tres paradas seleccionadas por el equipo Evenxa",
            "Pulsera digital y check-in express",
        ],
        schedule: [
            {
                time: "19:30",
                label: "Check-in",
                description: "Validacion de boletos y entrega de pulseras.",
            },
            {
                time: "20:15",
                label: "Salida",
                description: "Inicio de ruta desde Punto Reforma.",
            },
            {
                time: "00:30",
                label: "Cierre",
                description: "Regreso al punto inicial.",
            },
        ],
        ticketTiers: [
            {
                id: "tour",
                name: "Tour completo",
                price: 1200,
                description: "Incluye acceso a la ruta y transporte.",
                available: true,
            },
            {
                id: "tour-plus",
                name: "Tour Plus",
                price: 1680,
                description: "Incluye ruta, transporte y acceso preferente.",
                available: true,
            },
        ],
        policies: [
            "Presentate 30 minutos antes de la salida.",
            "El itinerario puede ajustarse por clima o transito.",
            "La compra no incluye consumos personales.",
        ],
    },
    {
        id: "evt-solar-sessions-2026",
        slug: "solar-sessions",
        title: "Solar Sessions",
        subtitle: "Tarde de musica independiente, gastronomia y mercado creativo.",
        description:
            "Solar Sessions es un encuentro al aire libre con bandas emergentes, marcas locales y espacios para convivir antes del atardecer.",
        location: "Guadalajara",
        venueName: "Foro Atemporal",
        address: "C. Argentina 75, Americana",
        city: "Guadalajara",
        date: "28 Nov 2026",
        time: "16:00",
        price: 650,
        image: heroImage,
        category: "Festival",
        status: "soon",
        organizer: "Evenxa Live",
        capacity: 850,
        tags: ["Indie", "Food", "Market"],
        highlights: [
            "Lineup curado con proyectos emergentes",
            "Mercado local y area gastronomica",
            "Ambiente al aire libre con acceso familiar",
        ],
        schedule: [
            {
                time: "16:00",
                label: "Apertura",
                description: "Ingreso, mercado creativo y food court.",
            },
            {
                time: "18:00",
                label: "Primer bloque",
                description: "Presentaciones de bandas invitadas.",
            },
            {
                time: "21:00",
                label: "Headliner",
                description: "Show de cierre en escenario principal.",
            },
        ],
        ticketTiers: [
            {
                id: "early",
                name: "Early access",
                price: 650,
                description: "Precio de lanzamiento por tiempo limitado.",
                available: false,
            },
            {
                id: "general",
                name: "General",
                price: 790,
                description: "Acceso general al festival.",
                available: true,
            },
        ],
        policies: [
            "Menores de edad ingresan acompanados por un adulto.",
            "No se permite reingreso despues de validar el boleto.",
            "Evento sujeto a lineamientos del venue.",
        ],
    },
    {
        id: "evt-mestiza-live-2026",
        slug: "mestiza-live",
        title: "Mestiza Live",
        subtitle: "Ritmos latinos, baile y una produccion pensada para celebrar.",
        description:
            "Mestiza Live junta musica latina, invitados especiales y una pista amplia para una experiencia vibrante de principio a fin.",
        location: "Monterrey",
        venueName: "Arena Barrio",
        address: "Calz. Madero 410, Centro",
        city: "Monterrey",
        date: "05 Dic 2026",
        time: "21:00",
        price: 980,
        image: heroImage,
        category: "Concierto",
        status: "available",
        organizer: "Evenxa Music",
        capacity: 2200,
        tags: ["Latino", "Baile", "Live"],
        highlights: [
            "Show en vivo con invitados especiales",
            "Pista central y zonas preferentes",
            "Compra y validacion digital en Evenxa",
        ],
        schedule: [
            {
                time: "21:00",
                label: "Puertas",
                description: "Apertura del venue y acceso a zonas.",
            },
            {
                time: "22:00",
                label: "DJ set",
                description: "Musica previa al show principal.",
            },
            {
                time: "23:15",
                label: "Mestiza Live",
                description: "Presentacion principal.",
            },
        ],
        ticketTiers: [
            {
                id: "general",
                name: "General",
                price: 980,
                description: "Acceso a pista general.",
                available: true,
            },
            {
                id: "preferente",
                name: "Preferente",
                price: 1750,
                description: "Zona preferente cercana al escenario.",
                available: true,
            },
        ],
        policies: [
            "Acceso permitido solo con boleto vigente.",
            "No se hacen cambios de zona el dia del evento.",
            "El venue puede negar acceso por incumplir reglas internas.",
        ],
    },
];
